In [35]:
import pandas as pd

url = 'https://raw.githubusercontent.com/Asunnya/terraform-miner/refs/heads/master/src/nlp_analysis/analysis_results_nlp/commits_com_clusters.jsonl'
df = pd.read_json(url, lines=True)
print(len(df))
display(df.head())

6749

,repo_name,commit_hash,author_name,author_date,msg_original,msg_clean_for_val,hdbscan_cluster_label,hdbscan_cluster_probability
0,airbnb_streamalert_ae70d90b,cac313c6ba3f6c9a3dcb26ef86f2d4b7f9525b61,Gavin,2022-07-20 13:39:10-0700,ISSUE-1318 Update AWS Terraform Provider (#132...,issue-1318 update aws terraform provider (#1328),15,0.793382
1,airbnb_streamalert_ae70d90b,b7971a0020c10049256020e20e1850776ba4b77e,ryandeivert,2020-08-26 15:22:02-0700,official release of v3.4.0 (#1292)\n\n* bumpin...,official release of v3.4.0 (#1292),16,1.000000
2,airbnb_streamalert_ae70d90b,bfde778bc216bff1dfd7372164fd20cb78012dee,ryandeivert,2020-08-05 15:03:43-0700,official release of v3.3.0 (#1287)\n\n* bumpin...,official release of v3.3.0 (#1287),16,1.000000
3,airbnb_streamalert_ae70d90b,4afadf5f51d02434ac1099ed22b89ab667514d5d,ryandeivert,2020-04-09 16:12:40-0700,official release of v3.2.0 (#1234)\n\n* bumpin...,official release of v3.2.0 (#1234),16,1.000000
4,airbnb_streamalert_ae70d90b,1714b1edf2e4f0e33427cb96ead66ae922c12e57,ryandeivert,2020-03-31 13:03:16-0700,official release of v3.1.1 (#1215)\n\n* bumpin...,official release of v3.1.1 (#1215),16,1.000000

In [36]:
df[['owner', 'name', 'gibberish']] = df['repo_name'].str.split('_', n=2, expand=True)
df = df.drop(columns=['gibberish'])
display(df.head())

,repo_name,commit_hash,author_name,author_date,msg_original,msg_clean_for_val,hdbscan_cluster_label,hdbscan_cluster_probability,owner,name
0,airbnb_streamalert_ae70d90b,cac313c6ba3f6c9a3dcb26ef86f2d4b7f9525b61,Gavin,2022-07-20 13:39:10-0700,ISSUE-1318 Update AWS Terraform Provider (#132...,issue-1318 update aws terraform provider (#1328),15,0.793382,airbnb,streamalert
1,airbnb_streamalert_ae70d90b,b7971a0020c10049256020e20e1850776ba4b77e,ryandeivert,2020-08-26 15:22:02-0700,official release of v3.4.0 (#1292)\n\n* bumpin...,official release of v3.4.0 (#1292),16,1.000000,airbnb,streamalert
2,airbnb_streamalert_ae70d90b,bfde778bc216bff1dfd7372164fd20cb78012dee,ryandeivert,2020-08-05 15:03:43-0700,official release of v3.3.0 (#1287)\n\n* bumpin...,official release of v3.3.0 (#1287),16,1.000000,airbnb,streamalert
3,airbnb_streamalert_ae70d90b,4afadf5f51d02434ac1099ed22b89ab667514d5d,ryandeivert,2020-04-09 16:12:40-0700,official release of v3.2.0 (#1234)\n\n* bumpin...,official release of v3.2.0 (#1234),16,1.000000,airbnb,streamalert
4,airbnb_streamalert_ae70d90b,1714b1edf2e4f0e33427cb96ead66ae922c12e57,ryandeivert,2020-03-31 13:03:16-0700,official release of v3.1.1 (#1215)\n\n* bumpin...,official release of v3.1.1 (#1215),16,1.000000,airbnb,streamalert

In [37]:
df['repo_URL'] = 'https://github.com/' + df['owner'] + '/' + df['name']
df['commit_URL'] = "=HYPERLINK(\""+df['repo_URL']+'/commit/'+df['commit_hash']+"\")"
display(df.head())

,repo_name,commit_hash,author_name,author_date,msg_original,msg_clean_for_val,hdbscan_cluster_label,hdbscan_cluster_probability,owner,name,repo_URL,commit_URL
0,airbnb_streamalert_ae70d90b,cac313c6ba3f6c9a3dcb26ef86f2d4b7f9525b61,Gavin,2022-07-20 13:39:10-0700,ISSUE-1318 Update AWS Terraform Provider (#132...,issue-1318 update aws terraform provider (#1328),15,0.793382,airbnb,streamalert,https://github.com/airbnb/streamalert,"=HYPERLINK(""https://github.com/airbnb/streamal..."
1,airbnb_streamalert_ae70d90b,b7971a0020c10049256020e20e1850776ba4b77e,ryandeivert,2020-08-26 15:22:02-0700,official release of v3.4.0 (#1292)\n\n* bumpin...,official release of v3.4.0 (#1292),16,1.000000,airbnb,streamalert,https://github.com/airbnb/streamalert,"=HYPERLINK(""https://github.com/airbnb/streamal..."
2,airbnb_streamalert_ae70d90b,bfde778bc216bff1dfd7372164fd20cb78012dee,ryandeivert,2020-08-05 15:03:43-0700,official release of v3.3.0 (#1287)\n\n* bumpin...,official release of v3.3.0 (#1287),16,1.000000,airbnb,streamalert,https://github.com/airbnb/streamalert,"=HYPERLINK(""https://github.com/airbnb/streamal..."
3,airbnb_streamalert_ae70d90b,4afadf5f51d02434ac1099ed22b89ab667514d5d,ryandeivert,2020-04-09 16:12:40-0700,official release of v3.2.0 (#1234)\n\n* bumpin...,official release of v3.2.0 (#1234),16,1.000000,airbnb,streamalert,https://github.com/airbnb/streamalert,"=HYPERLINK(""https://github.com/airbnb/streamal..."
4,airbnb_streamalert_ae70d90b,1714b1edf2e4f0e33427cb96ead66ae922c12e57,ryandeivert,2020-03-31 13:03:16-0700,official release of v3.1.1 (#1215)\n\n* bumpin...,official release of v3.1.1 (#1215),16,1.000000,airbnb,streamalert,https://github.com/airbnb/streamalert,"=HYPERLINK(""https://github.com/airbnb/streamal..."

In [38]:
df_sampled = df.sample(n=169, random_state=42)
display(df_sampled.head())
display(df_sampled.shape)

,repo_name,commit_hash,author_name,author_date,msg_original,msg_clean_for_val,hdbscan_cluster_label,hdbscan_cluster_probability,owner,name,repo_URL,commit_URL
6266,terraform-google-modules_terraform-google-kube...,1b7a845714cd86cbc3fbb7bf782b868330ca5fe9,Andrew Peabody,2024-09-13 14:00:21-0700,fix: correct gcfs_config value (#2095),fix: correct gcfs_config value (#2095),16,1.0,terraform-google-modules,terraform-google-kubernetes-engine,https://github.com/terraform-google-modules/te...,"=HYPERLINK(""https://github.com/terraform-googl..."
5402,ministryofjustice_modernisation-platform_08bf4e3f,79a8ccd608e1239b3af2b030954d3674f9612c75,dms1981,None,Move logging out of firewall policy module (#3...,move logging out of firewall policy module (#3...,16,1.0,ministryofjustice,modernisation-platform,https://github.com/ministryofjustice/modernisa...,"=HYPERLINK(""https://github.com/ministryofjusti..."
2895,GoogleCloudPlatform_cloud-foundation-fabric_59...,b6e0557bbbf7b024df7835aec00ed5fd1c4a7032,Julio Castillo,None,Simplify organization tags.tf locals (#1932)\n...,simplify organization tags.tf locals (#1932),16,1.0,GoogleCloudPlatform,cloud-foundation-fabric,https://github.com/GoogleCloudPlatform/cloud-f...,"=HYPERLINK(""https://github.com/GoogleCloudPlat..."
2181,coreos_tectonic-installer_c183a4a7,5fbe1af8b902e6a1ca10601ce0fb8b2ee14bead3,Lucas Servén Marín,None,Merge pull request #3114 from squat/fix_ca\n\n...,fix ca config.tf: bump tls provider to fix ca,16,1.0,coreos,tectonic-installer,https://github.com/coreos/tectonic-installer,"=HYPERLINK(""https://github.com/coreos/tectonic..."
2347,coreos_tectonic-installer_c183a4a7,7bc064e436c938050f09964654d175f8cb82a668,Quentin Machu,2017-05-03 16:07:11-0700,platforms/aws/route53: delete records before d...,platforms/aws/route53: delete records before d...,16,1.0,coreos,tectonic-installer,https://github.com/coreos/tectonic-installer,"=HYPERLINK(""https://github.com/coreos/tectonic..."

(169, 12)

In [39]:
import numpy as np
# sample size: used Cochran with 99% confidence level, 10% margin of error = 167.
n_total = 169
n_unique_per_file = 38
n_overlapping = 17
n_per_file = n_unique_per_file + n_overlapping
df_sampled['is_bugfix'] = ""
df_sampled['obs'] = ""
df_sampled = df_sampled[['commit_URL','is_bugfix', 'obs']]
all_indices = df_sampled.index.tolist()

np.random.shuffle(all_indices)

overlapping_indices = all_indices[:n_overlapping]

unique_indices = all_indices[n_overlapping:]

unique_indices_split = np.array_split(unique_indices, 4)

indices_file1 = overlapping_indices + unique_indices_split[0].tolist()
indices_file2 = overlapping_indices + unique_indices_split[1].tolist()
indices_file3 = overlapping_indices + unique_indices_split[2].tolist()
indices_file4 = overlapping_indices + unique_indices_split[3].tolist()

df_file1 = df_sampled.loc[indices_file1]
df_file2 = df_sampled.loc[indices_file2]
df_file3 = df_sampled.loc[indices_file3]
df_file4 = df_sampled.loc[indices_file4]

df_file1.to_csv('sample_heleno.csv', index=False)
df_file2.to_csv('sample_isadora.csv', index=False)
df_file3.to_csv('sample_vania.csv', index=False)
df_file4.to_csv('sample_joao.csv', index=False)